exclude: '\.snap$'
repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
      language_version: python3.7
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-xml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: no-commit-to-branch
    - id: trailing-whitespace
    - id: debug-statements
      language_version: python3.7
    - id: flake8
      log_file: '.artifacts/flake8.log'
      language_version: python3.7
    - id: requirements-txt-fixer
      args: ['requirements-base.txt', 'requirements-dev.txt', 'requirements-test.txt']
-   repo: git://github.com/getsentry/pre-commit-hooks
    rev: f3237d2d65af81d435c49dee3593dc8f03d23c2d
    hooks:
    - id: prettier
    - id: eslint
      args: ['--format=checkstyle']
      log_file: '.artifacts/eslint.checkstyle.xml'
