language: python
sudo: false
services:
  - redis-server
  - postgresql
python:
  - "3.6"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip/wheels
env:
  global:
    - NODE_ENV=production
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - TRAVIS_NODE_VERSION=8
install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn@0.27.5
  - make
script:
  - git --version
  - node_modules/.bin/eslint webapp --format=checkstyle > checkstyle.xml
  - flake8 > flake8.txt
  - py.test tests -v --cov . --cov-report="xml:coverage.xml" --junit-xml="junit.xml"
  - yarn test
after_success:
  - npm install -g @zeus-ci/cli
  - $(npm bin -g)/zeus upload -t "text/xml+xunit" junit.xml
  - $(npm bin -g)/zeus upload -t "text/xml+coverage" coverage.xml
  - $(npm bin -g)/zeus upload -t "text/xml+checkstyle" checkstyle.xml
  - $(npm bin -g)/zeus upload -t "text/plain+pycodestyle" flake8.txt
after_failure:
  - npm install -g @zeus-ci/cli
  - $(npm bin -g)/zeus upload -t "text/xml+xunit" junit.xml
  - $(npm bin -g)/zeus upload -t "text/xml+coverage" coverage.xml
  - $(npm bin -g)/zeus upload -t "text/xml+checkstyle" checkstyle.xml
  - $(npm bin -g)/zeus upload -t "text/plain+pycodestyle" flake8.txt
notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/c8e250c8-81ee-11e7-bf7a-0a580a280480/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  email: false
