language: python
sudo: false
services:
  - redis-server
  - postgresql
python:
  - "3.6"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
env:
  global:
    - NODE_ENV=production
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - TRAVIS_NODE_VERSION=8
install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn@0.27.5
  - make
script:
  - git --version
  - PATH=node_modules/.bin:$PATH pre-commit run -a
  - py.test tests -v --cov . --cov-report="xml:coverage.xml" --junit-xml=".artifacts/pytest.junit.xml"
  - node_modules/.bin/webpack --profile --json > .artifacts/webpack-stats.json
  - JEST_JUNIT_OUTPUT=.artifacts/jest.junit.xml yarn test -- --ci --testResultsProcessor="jest-junit"
after_success:
  - npm install -g @zeus-ci/cli
  - $(npm bin -g)/zeus upload -t "application/x-junit+xml" .artifacts/*.junit.xml
  - $(npm bin -g)/zeus upload -t "application/x-cobertura+xml" .artifacts/coverage.xml
  - $(npm bin -g)/zeus upload -t "application/x-cobertura+xml" .artifacts/coverage/cobertura-coverage.xml
  - $(npm bin -g)/zeus upload -t "application/x-checkstyle+xml" .artifacts/*.checkstyle.xml
  - $(npm bin -g)/zeus upload -t "text/x-pycodestyle" .artifacts/flake8.log
  - $(npm bin -g)/zeus upload -t "application/webpack-stats+json" .artifacts/webpack-stats.json
after_failure:
  - npm install -g @zeus-ci/cli
  - $(npm bin -g)/zeus upload -t "application/x-junit+xml" .artifacts/*.junit.xml
  - $(npm bin -g)/zeus upload -t "application/x-cobertura+xml" .artifacts/coverage.xml
  - $(npm bin -g)/zeus upload -t "application/x-cobertura+xml" .artifacts/coverage/cobertura-coverage.xml
  - $(npm bin -g)/zeus upload -t "application/x-checkstyle+xml" .artifacts/*.checkstyle.xml
  - $(npm bin -g)/zeus upload -t "text/x-pycodestyle" .artifacts/flake8.log
  - $(npm bin -g)/zeus upload -t "application/webpack-stats+json" .artifacts/webpack-stats.json
notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/c8e250c8-81ee-11e7-bf7a-0a580a280480/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  email: false
